package com.gsp.mastek.registration.model;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.gsp.mastek.common.entity.BaseEntity;

/**
 * OrganizationAddress generated by hbm2java
 */
@Entity
@Audited
public class OrganizationAddress extends BaseEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long organizationaddressId;
	
	private String buildingNumber;
	
	private String floorNumber;
	
	private String buildingName;
	
	private String street;
	
	private String locality;
	
	private String district;
	
	private String stateCd;
	
	private String pinCode;
	
	@NotAudited
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
	@JoinColumn(name = "organizationaddressId", referencedColumnName = "organizationaddressId")
	private Set<OrganizationContact> organizationContacts;

	public Long getOrganizationaddressId() {
		return organizationaddressId;
	}

	public void setOrganizationaddressId(Long organizationaddressId) {
		this.organizationaddressId = organizationaddressId;
	}

	public String getBuildingNumber() {
		return buildingNumber;
	}

	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	public String getFloorNumber() {
		return floorNumber;
	}

	public void setFloorNumber(String floorNumber) {
		this.floorNumber = floorNumber;
	}

	public String getBuildingName() {
		return buildingName;
	}

	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getLocality() {
		return locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getStateCd() {
		return stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	public String getPinCode() {
		return pinCode;
	}

	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}

	public Set<OrganizationContact> getOrganizationContacts() {
		return organizationContacts;
	}

	public void setOrganizationContacts(Set<OrganizationContact> organizationContacts) {
		this.organizationContacts = organizationContacts;
	}

	public void addOrganizationContact(OrganizationContact organizationContact) {
		if (this.organizationContacts == null) {
			this.organizationContacts = new HashSet<OrganizationContact>();
			this.organizationContacts.add(organizationContact);
		} else {
			this.organizationContacts.add(organizationContact);
		}
	}

	@Override
	public String toString() {
		return "OrganizationAddress [organizationaddressId=" + organizationaddressId + ", buildingNumber="
				+ buildingNumber + ", floorNumber=" + floorNumber + ", buildingName=" + buildingName + ", street="
				+ street + ", locality=" + locality + ", district=" + district + ", stateCd=" + stateCd + ", pinCode="
				+ pinCode + ", organizationContacts=" + organizationContacts + "]";
	}	

}
