package com.gsp.mastek.registration.model;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.envers.Audited;

import com.gsp.mastek.common.entity.BaseEntity;

/**
 * PartycontactPreference generated by hbm2java
 */
@Entity
@Audited
public class PartycontactPreference extends BaseEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long partycontactpreferenceId;
	
	private String preferredDay;
	
	private String preferredTimefrom;
	
	private String preferredTimeto;

	public Long getPartycontactpreferenceId() {
		return partycontactpreferenceId;
	}

	public void setPartycontactpreferenceId(Long partycontactpreferenceId) {
		this.partycontactpreferenceId = partycontactpreferenceId;
	}

	public String getPreferredDay() {
		return preferredDay;
	}

	public void setPreferredDay(String preferredDay) {
		this.preferredDay = preferredDay;
	}

	public String getPreferredTimefrom() {
		return preferredTimefrom;
	}

	public void setPreferredTimefrom(String preferredTimefrom) {
		this.preferredTimefrom = preferredTimefrom;
	}

	public String getPreferredTimeto() {
		return preferredTimeto;
	}

	public void setPreferredTimeto(String preferredTimeto) {
		this.preferredTimeto = preferredTimeto;
	}

	@Override
	public String toString() {
		return "PartycontactPreference [partycontactpreferenceId=" + partycontactpreferenceId + ", preferredDay="
				+ preferredDay + ", preferredTimefrom=" + preferredTimefrom + ", preferredTimeto=" + preferredTimeto
				+ "]";
	}
}
