package com.gsp.mastek.registration.model;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import com.gsp.mastek.common.entity.BaseEntity;

/**
 * Party generated by hbm2java
 */
@Entity
public class Party extends BaseEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long partyId;
	
	private String partyType;
	
	private String firstName;
	
	private String middleName;
	
	private String lastName;
	
	private String fatherFirstName;
	
	private String fatherMiddleName;
	
	private String fatherLastName;
	
	private String husbandFirstName;
	
	private String husbandMiddleName;
	
	private String husbandLastName;
	
	private String designation;
	
	private String gender;
	
	private Date dateOfBirth;
	
	private String isIndianCitizen;
	
	private String panNumber;
	
	private String passportNumber;
	
	private String aadharNumber;
	
	private String dinNumber;
	
	private String partyStatus;	
	
	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
	@JoinColumn(name = "partyId", referencedColumnName = "partyId")
	private Set<PartyAddress> partyAddresses;

	public Long getPartyId() {
		return partyId;
	}

	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	public String getPartyType() {
		return partyType;
	}

	public void setPartyType(String partyType) {
		this.partyType = partyType;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFatherFirstName() {
		return fatherFirstName;
	}

	public void setFatherFirstName(String fatherFirstName) {
		this.fatherFirstName = fatherFirstName;
	}

	public String getFatherMiddleName() {
		return fatherMiddleName;
	}

	public void setFatherMiddleName(String fatherMiddleName) {
		this.fatherMiddleName = fatherMiddleName;
	}

	public String getFatherLastName() {
		return fatherLastName;
	}

	public void setFatherLastName(String fatherLastName) {
		this.fatherLastName = fatherLastName;
	}

	public String getHusbandFirstName() {
		return husbandFirstName;
	}

	public void setHusbandFirstName(String husbandFirstName) {
		this.husbandFirstName = husbandFirstName;
	}

	public String getHusbandMiddleName() {
		return husbandMiddleName;
	}

	public void setHusbandMiddleName(String husbandMiddleName) {
		this.husbandMiddleName = husbandMiddleName;
	}

	public String getHusbandLastName() {
		return husbandLastName;
	}

	public void setHusbandLastName(String husbandLastName) {
		this.husbandLastName = husbandLastName;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getIsIndianCitizen() {
		return isIndianCitizen;
	}

	public void setIsIndianCitizen(String isIndianCitizen) {
		this.isIndianCitizen = isIndianCitizen;
	}

	public String getPanNumber() {
		return panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	public String getPassportNumber() {
		return passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	public String getAadharNumber() {
		return aadharNumber;
	}

	public void setAadharNumber(String aadharNumber) {
		this.aadharNumber = aadharNumber;
	}

	public String getDinNumber() {
		return dinNumber;
	}

	public void setDinNumber(String dinNumber) {
		this.dinNumber = dinNumber;
	}

	public String getPartyStatus() {
		return partyStatus;
	}

	public void setPartyStatus(String partyStatus) {
		this.partyStatus = partyStatus;
	}

	public Set<PartyAddress> getPartyAddresses() {
		return partyAddresses;
	}

	public void setPartyAddresses(Set<PartyAddress> partyAddresses) {
		this.partyAddresses = partyAddresses;
	}
	
	public void addPartyAddress(PartyAddress partyAddress) {
		if (this.partyAddresses == null) {
			this.partyAddresses = new HashSet<PartyAddress>();
			this.partyAddresses.add(partyAddress);
		} else {
			this.partyAddresses.add(partyAddress);
		}
	}

	@Override
	public String toString() {
		return "Party [partyId=" + partyId + ", partyType=" + partyType + ", firstName=" + firstName + ", middleName="
				+ middleName + ", lastName=" + lastName + ", fatherFirstName=" + fatherFirstName + ", fatherMiddleName="
				+ fatherMiddleName + ", fatherLastName=" + fatherLastName + ", husbandFirstName=" + husbandFirstName
				+ ", husbandMiddleName=" + husbandMiddleName + ", husbandLastName=" + husbandLastName + ", designation="
				+ designation + ", gender=" + gender + ", dateOfBirth=" + dateOfBirth + ", isIndianCitizen="
				+ isIndianCitizen + ", panNumber=" + panNumber + ", passportNumber=" + passportNumber
				+ ", aadharNumber=" + aadharNumber + ", dinNumber=" + dinNumber + ", partyStatus=" + partyStatus
				+ ", partyAddresses=" + partyAddresses + "]";
	}
	
}
