package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import com.gsp.mastek.common.vo.BaseVO;

/**
 * BusinessDtls generated by hbm2java
 */

public class BusinessDtlsVO extends BaseVO {

	private Long businessdtlsId;
	private String stateCd;
	private String stateJurisdiction;
	private String wardCircleSectorNum;
	private String centerJurisdiction;
	private String rangeCd;
	private String commissionarateCd;
	private String divisionCd;
	
	public Long getBusinessdtlsId() {
		return businessdtlsId;
	}
	public void setBusinessdtlsId(Long businessdtlsId) {
		this.businessdtlsId = businessdtlsId;
	}
	public String getStateCd() {
		return stateCd;
	}
	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}
	public String getStateJurisdiction() {
		return stateJurisdiction;
	}
	public void setStateJurisdiction(String stateJurisdiction) {
		this.stateJurisdiction = stateJurisdiction;
	}
	public String getWardCircleSectorNum() {
		return wardCircleSectorNum;
	}
	public void setWardCircleSectorNum(String wardCircleSectorNum) {
		this.wardCircleSectorNum = wardCircleSectorNum;
	}
	public String getCenterJurisdiction() {
		return centerJurisdiction;
	}
	public void setCenterJurisdiction(String centerJurisdiction) {
		this.centerJurisdiction = centerJurisdiction;
	}
	public String getRangeCd() {
		return rangeCd;
	}
	public void setRangeCd(String rangeCd) {
		this.rangeCd = rangeCd;
	}
	public String getCommissionarateCd() {
		return commissionarateCd;
	}
	public void setCommissionarateCd(String commissionarateCd) {
		this.commissionarateCd = commissionarateCd;
	}
	public String getDivisionCd() {
		return divisionCd;
	}
	public void setDivisionCd(String divisionCd) {
		this.divisionCd = divisionCd;
	}
	@Override
	public String toString() {
		return "BusinessDtlsVO [businessdtlsId=" + businessdtlsId + ", stateCd=" + stateCd + ", stateJurisdiction="
				+ stateJurisdiction + ", wardCircleSectorNum=" + wardCircleSectorNum + ", centerJurisdiction="
				+ centerJurisdiction + ", rangeCd=" + rangeCd + ", commissionarateCd=" + commissionarateCd
				+ ", divisionCd=" + divisionCd + "]";
	}
}
