package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import com.gsp.mastek.common.vo.BaseVO;

/**
 * GoodsDtls generated by hbm2java
 */

public class GoodsDtlsVO extends BaseVO {

	private Long goodsdtlsId;
	private String goodsDescription;
	private Long hsnCode;
	
	public Long getGoodsdtlsId() {
		return goodsdtlsId;
	}
	public void setGoodsdtlsId(Long goodsdtlsId) {
		this.goodsdtlsId = goodsdtlsId;
	}
	public String getGoodsDescription() {
		return goodsDescription;
	}
	public void setGoodsDescription(String goodsDescription) {
		this.goodsDescription = goodsDescription;
	}
	public Long getHsnCode() {
		return hsnCode;
	}
	public void setHsnCode(Long hsnCode) {
		this.hsnCode = hsnCode;
	}
	@Override
	public String toString() {
		return "GoodsDtlsVO [goodsdtlsId=" + goodsdtlsId + ", goodsDescription=" + goodsDescription + ", hsnCode="
				+ hsnCode + "]";
	}

}
