package com.gsp.mastek.registration.vo;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import com.gsp.mastek.common.vo.BaseVO;
import com.gsp.mastek.registration.enums.ContactType;

/**
 * OrganizationContact generated by hbm2java
 */

public class OrganizationContactVO extends BaseVO {

	private Long organizationcontactId;
	private ContactType contactType;
	private String contactValue;
	private Long addressId;
	
	private Set<OrganizationContactpreferenceVO> organizationContactpreferences = new HashSet<OrganizationContactpreferenceVO>(
			0);
	
	public Long getOrganizationcontactId() {
		return organizationcontactId;
	}
	public void setOrganizationcontactId(Long organizationcontactId) {
		this.organizationcontactId = organizationcontactId;
	}	
	
	public ContactType getContactType() {
		return contactType;
	}
	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}
	public String getContactValue() {
		return contactValue;
	}
	public void setContactValue(String contactValue) {
		this.contactValue = contactValue;
	}
	public Long getAddressId() {
		return addressId;
	}
	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}
	public Set<OrganizationContactpreferenceVO> getOrganizationContactpreferences() {
		return organizationContactpreferences;
	}
	public void setOrganizationContactpreferences(Set<OrganizationContactpreferenceVO> organizationContactpreferences) {
		this.organizationContactpreferences = organizationContactpreferences;
	}
	@Override
	public String toString() {
		return "OrganizationContactVO [organizationcontactId=" + organizationcontactId + ", contactType=" + contactType
				+ ", contactValue=" + contactValue + ", addressId=" + addressId + ", organizationContactpreferences="
				+ organizationContactpreferences + "]";
	}

}
