package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import com.gsp.mastek.common.vo.BaseVO;

/**
 * OrganizationAddress generated by hbm2java
 */

public class OrganizationAddressVO extends BaseVO {

	private Long organizationaddressId;
	private String buildingNumber;
	private String floorNumber;
	private String buildingName;
	private String street;
	private String locality;
	private String district;
	private String stateCd;
	private Integer pinCode;
	private Set<OrganizationContactVO> organizationContacts = new HashSet<OrganizationContactVO>(0);
	
	public Long getOrganizationaddressId() {
		return organizationaddressId;
	}
	public void setOrganizationaddressId(Long organizationaddressId) {
		this.organizationaddressId = organizationaddressId;
	}
	public String getBuildingNumber() {
		return buildingNumber;
	}
	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}
	public String getFloorNumber() {
		return floorNumber;
	}
	public void setFloorNumber(String floorNumber) {
		this.floorNumber = floorNumber;
	}
	public String getBuildingName() {
		return buildingName;
	}
	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}
	public String getStreet() {
		return street;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getLocality() {
		return locality;
	}
	public void setLocality(String locality) {
		this.locality = locality;
	}
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getStateCd() {
		return stateCd;
	}
	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}
	public Integer getPinCode() {
		return pinCode;
	}
	public void setPinCode(Integer pinCode) {
		this.pinCode = pinCode;
	}
	public Set<OrganizationContactVO> getOrganizationContacts() {
		return organizationContacts;
	}
	public void setOrganizationContacts(Set<OrganizationContactVO> organizationContacts) {
		this.organizationContacts = organizationContacts;
	}
	@Override
	public String toString() {
		return "OrganizationAddressVO [organizationaddressId=" + organizationaddressId + ", buildingNumber="
				+ buildingNumber + ", floorNumber=" + floorNumber + ", buildingName=" + buildingName + ", street="
				+ street + ", locality=" + locality + ", district=" + district + ", stateCd=" + stateCd + ", pinCode="
				+ pinCode + ", organizationContacts=" + organizationContacts + "]";
	}

}
