package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import com.gsp.mastek.common.vo.BaseVO;

/**
 * OrganizationContactpreference generated by hbm2java
 */

public class OrganizationContactpreferenceVO extends BaseVO {

	private Long organizationcontactpreferenceId;
	private String preferredDay;
	private String preferredTimefrom;
	private String preferredTimeto;
	private Long contactId;
	
	public Long getOrganizationcontactpreferenceId() {
		return organizationcontactpreferenceId;
	}
	public void setOrganizationcontactpreferenceId(Long organizationcontactpreferenceId) {
		this.organizationcontactpreferenceId = organizationcontactpreferenceId;
	}
	public String getPreferredDay() {
		return preferredDay;
	}
	public void setPreferredDay(String preferredDay) {
		this.preferredDay = preferredDay;
	}
	public String getPreferredTimefrom() {
		return preferredTimefrom;
	}
	public void setPreferredTimefrom(String preferredTimefrom) {
		this.preferredTimefrom = preferredTimefrom;
	}
	public String getPreferredTimeto() {
		return preferredTimeto;
	}
	public void setPreferredTimeto(String preferredTimeto) {
		this.preferredTimeto = preferredTimeto;
	}
	public Long getContactId() {
		return contactId;
	}
	public void setContactId(Long contactId) {
		this.contactId = contactId;
	}
	
	@Override
	public String toString() {
		return "OrganizationContactpreferenceVO [organizationcontactpreferenceId=" + organizationcontactpreferenceId
				+ ", preferredDay=" + preferredDay + ", preferredTimefrom=" + preferredTimefrom + ", preferredTimeto="
				+ preferredTimeto + ", contactId=" + contactId + "]";
	}

}
