package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import com.gsp.mastek.common.vo.BaseVO;

/**
 * PartyContact generated by hbm2java
 */

public class PartyContactVO extends BaseVO {

	private Long partycontactId;
	private String contactType;
	private String contactValue;	
	private Set<PartycontactPreferenceVO> partycontactPreferences = new HashSet<PartycontactPreferenceVO>(0);

	public Long getPartycontactId() {
		return partycontactId;
	}

	public void setPartycontactId(Long partycontactId) {
		this.partycontactId = partycontactId;
	}

	public String getContactType() {
		return contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public String getContactValue() {
		return contactValue;
	}

	public void setContactValue(String contactValue) {
		this.contactValue = contactValue;
	}

	public Set<PartycontactPreferenceVO> getPartycontactPreferences() {
		return partycontactPreferences;
	}

	public void setPartycontactPreferences(Set<PartycontactPreferenceVO> partycontactPreferences) {
		this.partycontactPreferences = partycontactPreferences;
	}

	@Override
	public String toString() {
		return "PartyContact [partycontactId=" + partycontactId + ", contactType=" + contactType + ", contactValue="
				+ contactValue + ", partycontactPreferences=" + partycontactPreferences + "]";
	}
}
