package com.gsp.mastek.registration.vo;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import com.gsp.mastek.common.vo.BaseVO;

/**
 * PartyAddress generated by hbm2java
 */

public class PartyAddressVO extends BaseVO {

	private Long partyaddressId;
	private String buildingNumber;
	private String floorNumber;
	private String buildingName;
	private String street;
	private String locality;
	private String district;
	private String stateCd;
	private Integer pinCode;
	private Set<PartyContactVO> partyContacts = new HashSet<PartyContactVO>(0);
	
	public Long getPartyaddressId() {
		return partyaddressId;
	}
	public void setPartyaddressId(Long partyaddressId) {
		this.partyaddressId = partyaddressId;
	}
	public String getBuildingNumber() {
		return buildingNumber;
	}
	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber;
	}
	public String getFloorNumber() {
		return floorNumber;
	}
	public void setFloorNumber(String floorNumber) {
		this.floorNumber = floorNumber;
	}
	public String getBuildingName() {
		return buildingName;
	}
	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}
	public String getStreet() {
		return street;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getLocality() {
		return locality;
	}
	public void setLocality(String locality) {
		this.locality = locality;
	}
	public String getDistrict() {
		return district;
	}
	public void setDistrict(String district) {
		this.district = district;
	}
	public String getStateCd() {
		return stateCd;
	}
	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}
	public Integer getPinCode() {
		return pinCode;
	}
	public void setPinCode(Integer pinCode) {
		this.pinCode = pinCode;
	}
	public Set<PartyContactVO> getPartyContacts() {
		return partyContacts;
	}
	public void setPartyContacts(Set<PartyContactVO> partyContacts) {
		this.partyContacts = partyContacts;
	}
	@Override
	public String toString() {
		return "PartyAddress [partyaddressId=" + partyaddressId + ", buildingNumber=" + buildingNumber
				+ ", floorNumber=" + floorNumber + ", buildingName=" + buildingName + ", street=" + street
				+ ", locality=" + locality + ", district=" + district + ", stateCd=" + stateCd + ", pinCode=" + pinCode
				+ ", partyContacts=" + partyContacts + "]";
	}
}
