package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import com.gsp.mastek.common.vo.BaseVO;

/**
 * PartycontactPreference generated by hbm2java
 */

public class PartycontactPreferenceVO extends BaseVO {

	private Long partycontactpreferenceId;
	private String preferredDay;
	private String preferredTimefrom;
	private Long preferredTimeto;
	
	public Long getPartycontactpreferenceId() {
		return partycontactpreferenceId;
	}
	public void setPartycontactpreferenceId(Long partycontactpreferenceId) {
		this.partycontactpreferenceId = partycontactpreferenceId;
	}
	public String getPreferredDay() {
		return preferredDay;
	}
	public void setPreferredDay(String preferredDay) {
		this.preferredDay = preferredDay;
	}
	public String getPreferredTimefrom() {
		return preferredTimefrom;
	}
	public void setPreferredTimefrom(String preferredTimefrom) {
		this.preferredTimefrom = preferredTimefrom;
	}
	public Long getPreferredTimeto() {
		return preferredTimeto;
	}
	public void setPreferredTimeto(Long preferredTimeto) {
		this.preferredTimeto = preferredTimeto;
	}
	@Override
	public String toString() {
		return "PartycontactPreferenceVO [partycontactpreferenceId=" + partycontactpreferenceId + ", preferredDay="
				+ preferredDay + ", preferredTimefrom=" + preferredTimefrom + ", preferredTimeto=" + preferredTimeto
				+ "]";
	}

}
