package com.gsp.mastek.registration.VO;
// Generated 24 Apr, 2017 3:18:39 PM by Hibernate Tools 5.2.1.Final

import com.gsp.mastek.common.vo.BaseVO;

/**
 * ServiceDtls generated by hbm2java
 */

public class ServiceDtlsVO extends BaseVO {

	private Long servicedtlsId;
	private String serviceDescription;
	private Integer sacCode;
	
	public Long getServicedtlsId() {
		return servicedtlsId;
	}
	public void setServicedtlsId(Long servicedtlsId) {
		this.servicedtlsId = servicedtlsId;
	}
	public String getServiceDescription() {
		return serviceDescription;
	}
	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}
	public Integer getSacCode() {
		return sacCode;
	}
	public void setSacCode(Integer sacCode) {
		this.sacCode = sacCode;
	}
	
	@Override
	public String toString() {
		return "ServiceDtlsVO [servicedtlsId=" + servicedtlsId + ", serviceDescription=" + serviceDescription
				+ ", sacCode=" + sacCode + "]";
	}
}
